# Generated by Django 4.0 on 2023-04-12 22:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('TN', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('VD', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестигиверы'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('PT', 'Зельевары'), ('MS', 'Мастера заклинаний')], default='VD', max_length=2)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
